<img width="200" style="float:right" src="https://github.com/danielscarvalho/Insper-DS-Dicas/blob/master/Insper-Logo.png?raw=true">

# Computação para Ciências dos Dados

<sub><a href="https://www.insper.edu.br/pos-graduacao/programas-avancados/programa-avancado-em-data-science-e-decisao/">PÓS-GRADUAÇÃO EM DATA SCIENCE E DECISÃO</a></sub>

## Dica do Dia: 006

O objetivo desta dica do dia é aprender sobre o pandas-profiling, importar dados e realizar análise automatizada gerando relatório em HTML.

> Todos os dias no período de contingência pelo Coronavirus (COVID-19) vamos enviar uma breve dica sobre Python para ciências dos dados em um jupyter notebook, conteúdo adicional ao curso que pode ser utilizado nos projetos

### Pandas-Profiling

O Pandas Profiling é uma ferramenta sofisticada para identificar as características dos dados em um dataframe Pandas (Nutela). É interessante para que o cientista de dados tenha uma boa perspectiva da qualidade dos dados e quais os tipos de análise que podem ser feitas, quais amostras são interessantes, quais podem ser descartados e assim por diante...

Primeiramente a instalação com o PIP:

In [1]:
!pip install pandas-profiling

Requirement already satisfied: pandas-profiling in /x4n/opt/anaconda3/lib/python3.6/site-packages (2.3.0)
Requirement already satisfied: astropy in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pandas-profiling) (3.1.2)
Requirement already satisfied: confuse>=1.0.0 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pandas-profiling) (1.0.0)
Requirement already satisfied: htmlmin>=0.1.12 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pandas-profiling) (0.1.12)
Requirement already satisfied: matplotlib>=1.4 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pandas-profiling) (3.0.3)
Requirement already satisfied: missingno>=0.4.2 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pandas-profiling) (0.4.2)
Requirement already satisfied: jinja2>=2.8 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pandas-profiling) (2.10)
Requirement already satisfied: phik>=0.9.8 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pandas-profiling) (0.9.8)
Requirement already satisfied: pandas>=0.19 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pandas-profiling) (0.24.2)
Requirement already satisfied: numpy>=1.13.0 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from astropy->pandas-profiling) (1.16.2)
Requirement already satisfied: pyyaml in /x4n/opt/anaconda3/lib/python3.6/site-packages (from confuse>=1.0.0->pandas-profiling) (5.1)
Requirement already satisfied: cycler>=0.10 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from matplotlib>=1.4->pandas-profiling) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from matplotlib>=1.4->pandas-profiling) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from matplotlib>=1.4->pandas-profiling) (2.3.1)
Requirement already satisfied: python-dateutil>=2.1 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from matplotlib>=1.4->pandas-profiling) (2.8.0)
Requirement already satisfied: scipy in /x4n/opt/anaconda3/lib/python3.6/site-packages (from missingno>=0.4.2->pandas-profiling) (1.4.1)
Requirement already satisfied: seaborn in /x4n/opt/anaconda3/lib/python3.6/site-packages (from missingno>=0.4.2->pandas-profiling) (0.9.0)
Requirement already satisfied: MarkupSafe>=0.23 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from jinja2>=2.8->pandas-profiling) (1.1.1)
Requirement already satisfied: nbconvert>=5.3.1 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from phik>=0.9.8->pandas-profiling) (5.4.1)
Requirement already satisfied: pytest-pylint>=0.13.0 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from phik>=0.9.8->pandas-profiling) (0.14.1)
Requirement already satisfied: pytest>=4.0.2 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from phik>=0.9.8->pandas-profiling) (4.3.1)
Requirement already satisfied: jupyter-client>=5.2.3 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from phik>=0.9.8->pandas-profiling) (5.2.4)
Requirement already satisfied: numba>=0.38.1 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from phik>=0.9.8->pandas-profiling) (0.43.1)
Requirement already satisfied: pytz>=2011k in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pandas>=0.19->pandas-profiling) (2018.9)
Requirement already satisfied: six in /x4n/opt/anaconda3/lib/python3.6/site-packages (from cycler>=0.10->matplotlib>=1.4->pandas-profiling) (1.12.0)
Requirement already satisfied: setuptools in /x4n/opt/anaconda3/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=1.4->pandas-profiling) (40.8.0)
Requirement already satisfied: mistune>=0.8.1 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.8.4)
Requirement already satisfied: pygments in /x4n/opt/anaconda3/lib/python3.6/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (2.3.1)
Requirement already satisfied: traitlets>=4.2 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (4.3.2)
Requirement already satisfied: jupyter_core in /x4n/opt/anaconda3/lib/python3.6/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (4.4.0)
Requirement already satisfied: nbformat>=4.4 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (4.4.0)
Requirement already satisfied: entrypoints>=0.2.2 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.3)
Requirement already satisfied: bleach in /x4n/opt/anaconda3/lib/python3.6/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (3.1.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (1.4.2)
Requirement already satisfied: testpath in /x4n/opt/anaconda3/lib/python3.6/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.4.2)
Requirement already satisfied: defusedxml in /x4n/opt/anaconda3/lib/python3.6/site-packages (from nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.5.0)
Requirement already satisfied: pylint>=1.4.5 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (2.3.1)
Requirement already satisfied: py>=1.5.0 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (1.8.0)
Requirement already satisfied: attrs>=17.4.0 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (19.1.0)
Requirement already satisfied: atomicwrites>=1.0 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (1.3.0)
Requirement already satisfied: pluggy>=0.7 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (0.9.0)
Requirement already satisfied: more-itertools>=4.0.0 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pytest>=4.0.2->phik>=0.9.8->pandas-profiling) (6.0.0)
Requirement already satisfied: pyzmq>=13 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from jupyter-client>=5.2.3->phik>=0.9.8->pandas-profiling) (18.0.0)
Requirement already satisfied: tornado>=4.1 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from jupyter-client>=5.2.3->phik>=0.9.8->pandas-profiling) (6.0.2)
Requirement already satisfied: llvmlite>=0.28.0dev0 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from numba>=0.38.1->phik>=0.9.8->pandas-profiling) (0.28.0)
Requirement already satisfied: ipython_genutils in /x4n/opt/anaconda3/lib/python3.6/site-packages (from traitlets>=4.2->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.2.0)
Requirement already satisfied: decorator in /x4n/opt/anaconda3/lib/python3.6/site-packages (from traitlets>=4.2->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (4.4.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from nbformat>=4.4->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (3.0.1)
Requirement already satisfied: webencodings in /x4n/opt/anaconda3/lib/python3.6/site-packages (from bleach->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.5.1)
Requirement already satisfied: astroid<3,>=2.2.0 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (2.2.5)
Requirement already satisfied: isort<5,>=4.2.5 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (4.3.16)
Requirement already satisfied: mccabe<0.7,>=0.6 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (0.6.1)
Requirement already satisfied: pyrsistent>=0.14.0 in /x4n/opt/anaconda3/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert>=5.3.1->phik>=0.9.8->pandas-profiling) (0.14.11)
Requirement already satisfied: lazy-object-proxy in /x4n/opt/anaconda3/lib/python3.6/site-packages (from astroid<3,>=2.2.0->pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (1.3.1)
Requirement already satisfied: typed-ast>=1.3.0; implementation_name == "cpython" in /x4n/opt/anaconda3/lib/python3.6/site-packages (from astroid<3,>=2.2.0->pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (1.3.1)
Requirement already satisfied: wrapt in /x4n/opt/anaconda3/lib/python3.6/site-packages (from astroid<3,>=2.2.0->pylint>=1.4.5->pytest-pylint>=0.13.0->phik>=0.9.8->pandas-profiling) (1.11.1)

Importação das bibliotecas

In [2]:
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

Carga de dados no dataframe Pandas, esta é a mesma "tabela" que utilizamos em uma dica anterior

In [7]:
df_coronav = pd.read_csv('data/corona/COVID19_open_line_list.csv')

In [18]:
df_coronav.sample(10)

,ID,age,sex,city,province,country,wuhan(0)_not_wuhan(1),latitude,longitude,geo_resolution,...,Unnamed_35,Unnamed_36,Unnamed_37,Unnamed_38,Unnamed_39,Unnamed_40,Unnamed_41,Unnamed_42,Unnamed_43,Unnamed_44
5555,5626.0,NaN,NaN,Xinyu City,Jiangxi,China,1.0,27.845460,114.8515,admin2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8836,9136.0,NaN,NaN,Dongguan City,Guangdong,China,1.0,22.933360,113.8738,admin2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6456,6734.0,NaN,NaN,Hefei City,Anhui,China,1.0,31.794440,117.3428,admin2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8789,9089.0,NaN,NaN,Dongguan City,Guangdong,China,1.0,22.933360,113.8738,admin2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11277,11583.0,NaN,NaN,NaN,North Gyeongsang,South Korea,1.0,36.317400,128.7493,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3854,3912.0,NaN,NaN,NaN,Shaanxi,China,1.0,35.264580,108.8832,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10976,11276.0,26,male,National Centre for Infectious Diseases,NaN,Singapore,1.0,1.322098,103.8472,point,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4389,4447.0,NaN,NaN,NaN,Henan,China,1.0,33.903350,113.6136,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11280,11586.0,NaN,NaN,NaN,North Gyeongsang,South Korea,1.0,36.317400,128.7493,admin1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_coronav.describe()

,ID,wuhan(0)_not_wuhan(1),latitude,longitude,chronic_disease_binary,Unnamed_33,Unnamed_34,Unnamed_35,Unnamed_36,Unnamed_37,Unnamed_38,Unnamed_39,Unnamed_40,Unnamed_41,Unnamed_42,Unnamed_43,Unnamed_44
count,13173.000000,13170.0,13147.000000,13147.000000,18.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,6769.250436,1.0,31.994650,110.495353,0.722222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3920.886020,0.0,7.536335,27.985144,0.460889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,1.0,-37.813600,-124.953070,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,3351.000000,1.0,27.905380,111.729600,0.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,6865.000000,1.0,31.759410,115.441800,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,10180.000000,1.0,35.781340,120.440400,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,13479.000000,1.0,69.649468,153.400000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

A ferramenta vai ler os dados do dataframe e gerar um relatório detalhado...

Isso demora, depende do volume de dados do seu dataframe...

In [10]:
profile = ProfileReport(df_coronav, title='Pandas Profiling Report')

Salvando o relatório em HTML:

In [13]:
profile.to_file(output_file="coronav_profile.html")

Visualizar a página HTML no Jupyter Notebook, faça uma boa análise no relatório gerado de forma automatizada:

In [16]:
%%html

<iframe src="coronav_profile.html" width="100%" height="800px"></iframe>

Para saber mais vejam o site do pandas-profiling:

https://github.com/pandas-profiling/pandas-profiling